### PR TITLE
Record updated tag names on project

### LINKED ISSUE #570: Adding a new tag in an update request log request silently fails if column doesn't already exist
**Situation:** 
I want to use the OpenPipe client to add a new log tag but I noticed if that if the tag column doesn't already exist, the updateLogTag request silently fails. The response object says one request was matched (like it was successfully updated), but the tag wasn't actually added. 

In order to make it work, you need to ensure the tag column exists by adding it to a request from the OpenAI OpenPipe client. Once the column exists, then you can just use the updateLogTags normally. 

I think the fix should be to check if the tag doesn't exist when calling updateLogTags, then it creates the column and updates the tag.

### PR DESCRIPTION
**Pull request by arcticfly**
Fixes https://github.com/OpenPipe/OpenPipe/issues/570

We should also cache tag names that come in via the updateLogTags endpoint.

### CODE REVIEW

File: app/src/utils/recordRequest.ts [hunk 1]
```diff
@@ -234,6 +234,12 @@ async function createTags(projectId: string, loggedCallId: string, tags: Record<
 
   await kysely.insertInto("LoggedCallTag").values(tagsToCreate).execute();
 
+  const tagNames = tagsToCreate.map((tag) => tag.name);
+
+  await recordTagNames(projectId, tagNames);
```
Comment (corbt) [inline app/src/utils/recordRequest.ts]: Can we just do `void recordTagNames(projectId, tagNames).catch(e => captureException(e)` to avoid the latency hit?

**Review by corbt — APPROVED** [review]

File: app/src/utils/recordRequest.ts (hunk 1 above)
Comment (arcticfly) [reply app/src/utils/recordRequest.ts]: Good idea
